name: Main

on:
  push:
    branches:
      - "main"

jobs:
  create-latest-tag:
    name: Create latest tag
    runs-on: ubuntu-latest
    steps:
      - name: Label latest release
        uses: actions/github-script@v6
        with:
          script: |
            const createLatestTag = require('.github/actions/createLatestTag.js')
            await createLatestTag({github, context, core})